# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: in.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='in.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x08in.proto\"F\n\x06Square\x12\r\n\x05value\x18\x03 \x01(\x05\x12\x16\n\x0eneighbor_right\x18\x04 \x01(\x08\x12\x15\n\rneighbor_down\x18\x07 \x01(\x08\"\"\n\x06Puzzle\x12\x18\n\x07squares\x18\x02 \x03(\x0b\x32\x07.Square\"\"\n\x06Result\x12\x18\n\x07puzzles\x18\x01 \x03(\x0b\x32\x07.Puzzleb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SQUARE = _descriptor.Descriptor(
  name='Square',
  full_name='Square',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Square.value', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_right', full_name='Square.neighbor_right', index=1,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_down', full_name='Square.neighbor_down', index=2,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=82,
)


_PUZZLE = _descriptor.Descriptor(
  name='Puzzle',
  full_name='Puzzle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='squares', full_name='Puzzle.squares', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=118,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='puzzles', full_name='Result.puzzles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=154,
)

_PUZZLE.fields_by_name['squares'].message_type = _SQUARE
_RESULT.fields_by_name['puzzles'].message_type = _PUZZLE
DESCRIPTOR.message_types_by_name['Square'] = _SQUARE
DESCRIPTOR.message_types_by_name['Puzzle'] = _PUZZLE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

Square = _reflection.GeneratedProtocolMessageType('Square', (_message.Message,), dict(
  DESCRIPTOR = _SQUARE,
  __module__ = 'in_pb2'
  # @@protoc_insertion_point(class_scope:Square)
  ))
_sym_db.RegisterMessage(Square)

Puzzle = _reflection.GeneratedProtocolMessageType('Puzzle', (_message.Message,), dict(
  DESCRIPTOR = _PUZZLE,
  __module__ = 'in_pb2'
  # @@protoc_insertion_point(class_scope:Puzzle)
  ))
_sym_db.RegisterMessage(Puzzle)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'in_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
