# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: out.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='out.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tout.proto\".\n\x0ePuzzleSolution\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x05\"0\n\x0cSolvedResult\x12 \n\x07puzzles\x18\x01 \x03(\x0b\x32\x0f.PuzzleSolutionb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PUZZLESOLUTION = _descriptor.Descriptor(
  name='PuzzleSolution',
  full_name='PuzzleSolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='PuzzleSolution.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='PuzzleSolution.values', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=59,
)


_SOLVEDRESULT = _descriptor.Descriptor(
  name='SolvedResult',
  full_name='SolvedResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='puzzles', full_name='SolvedResult.puzzles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=109,
)

_SOLVEDRESULT.fields_by_name['puzzles'].message_type = _PUZZLESOLUTION
DESCRIPTOR.message_types_by_name['PuzzleSolution'] = _PUZZLESOLUTION
DESCRIPTOR.message_types_by_name['SolvedResult'] = _SOLVEDRESULT

PuzzleSolution = _reflection.GeneratedProtocolMessageType('PuzzleSolution', (_message.Message,), dict(
  DESCRIPTOR = _PUZZLESOLUTION,
  __module__ = 'out_pb2'
  # @@protoc_insertion_point(class_scope:PuzzleSolution)
  ))
_sym_db.RegisterMessage(PuzzleSolution)

SolvedResult = _reflection.GeneratedProtocolMessageType('SolvedResult', (_message.Message,), dict(
  DESCRIPTOR = _SOLVEDRESULT,
  __module__ = 'out_pb2'
  # @@protoc_insertion_point(class_scope:SolvedResult)
  ))
_sym_db.RegisterMessage(SolvedResult)


# @@protoc_insertion_point(module_scope)
